name: Update README

on:
  schedule:
    - cron: '* * * * *' # Update every 30 minutes
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: Readme-Workflows/recent-activity@2.3.1
        env:
          PROFILE_LATEST_ACTIVITY: ${{ secrets.PROFILE_LATEST_ACTIVITY }}
